### PR TITLE
feat(shortcut): Add shortcut key binding in settings panel

### PR DESCRIPTION
**Pull request by Theigrams**
Now we can bind the command shortcuts in the settings panel.

### CODE REVIEW

**Comment by huyz** [comment]
Awesome.

Would it be possible to have a shortcut to paste in the URL in the clipboard and have the title be fetched and filled in (after a slight delay if necessary).  This would be similar to how I do things in Obsidian with https://github.com/zolrath/obsidian-auto-link-title

**Comment by PaulKinlan** [comment]
@Theigrams - Sorry I missed this. Will review.

@huyz - I have been thinking of something similar. Will investigate.

**Comment by huyz** [comment]
> @huyz - I have been thinking of something similar. Will investigate.

Followed up here: https://github.com/PaulKinlan/logseq-webpage-title/issues/26

**Comment by PaulKinlan** [comment]
Just a quick update - I merged this to another branch and cleaned up some of the code and made some changes, for example, I detect changes to the settings and auto-apply them; all options are off by-default etc.

@Theigrams - thank you very much for all the work you did on this. It was amazing.

**Comment by Theigrams** [comment]
> Just a quick update - I merged this to another branch and cleaned up some of the code and made some changes, for example, I detect changes to the settings and auto-apply them; all options are off by-default etc.
> 
> @Theigrams - thank you very much for all the work you did on this. It was amazing.

Also thank you a lot for your excellent work, it brought us a great convenience.

**Pull request merged**
